// Package llm defines the LLM port for Job Tendencies.
// Two interfaces are exposed: AdapterGenerator for board adapter generation and
// ListingExtractor for structured field extraction from raw listings.
// This package has no SDK import; the Anthropic implementation lives in infra/llm.
package llm

import (
	"time"

	"github.com/g-trinh/job-tendencies/internal/domain/kernel"
)

// FetchMode specifies whether the board exposes a JSON/GraphQL API or HTML pages.
type FetchMode string

const (
	// FetchModeJSONAPI targets the board's internal JSON/GraphQL search endpoint.
	// Preferred over HTML because endpoints are more stable than rendered markup.
	FetchModeJSONAPI FetchMode = "json_api"
	// FetchModeHTML falls back to CSS-selector scraping of rendered HTML pages.
	FetchModeHTML FetchMode = "html"
)

// ListingFetch specifies whether the adapter needs a separate detail-page request
// or can reuse the search-result payload directly.
type ListingFetch string

const (
	// ListingFetchDetailPage fetches each listing URL separately.
	ListingFetchDetailPage ListingFetch = "detail_page"
	// ListingFetchUseSearchPayload uses the search-result entry as the full payload.
	ListingFetchUseSearchPayload ListingFetch = "use_search_payload"
)

// PaginationKind specifies the pagination mechanism used by the board.
type PaginationKind string

const (
	// PaginationKindQueryParam advances pages via an incrementing query parameter.
	PaginationKindQueryParam PaginationKind = "query_param"
	// PaginationKindCursor advances pages via an opaque cursor token.
	PaginationKindCursor PaginationKind = "cursor"
)

// AdapterSpec is the declarative configuration for scraping one job board.
// It is generated by the LLM (via AdapterGenerator), stored in the database,
// and must be reviewed and approved by the user before going live. It is evaluated
// by the generic scraper — never compiled or executed as code.
//
// See docs/architecture/pipeline.md §1 for the full YAML reference.
type AdapterSpec struct {
	// Board is the machine-readable board identifier (e.g. "welcometothejungle").
	Board       string            `json:"board"`
	FetchMode   FetchMode         `json:"fetch_mode"`
	Search      SearchConfig      `json:"search"`
	Listing     ListingConfig     `json:"listing"`
	Incremental IncrementalConfig `json:"incremental"`
}

// SearchConfig describes the search/index crawl phase for a board.
type SearchConfig struct {
	// URLTemplate is the search endpoint with placeholders such as {keywords} and {location}.
	URLTemplate string `json:"url_template"`
	// Method is "GET" or "POST". Defaults to "GET".
	Method string `json:"method"`
	// BodyTemplate is a JSON body template for POST/GraphQL requests; empty for GET.
	BodyTemplate string `json:"body_template,omitempty"`
	// ParamMap maps board query parameter names to profile field paths
	// (e.g. "keywords" → "profile.search.keywords").
	ParamMap map[string]string `json:"param_map"`
	// Pagination describes how to advance through result pages.
	Pagination PaginationConfig `json:"pagination"`
	// ResultNodePath is a JSONPath expression (json_api) or CSS selector (html)
	// pointing to the array of result cards in the response.
	ResultNodePath string `json:"result_node_path"`
	// ResultFields maps semantic field names to JSONPath/CSS selectors within each card.
	// Required keys: "listing_url". Optional: "posted_at", "external_id".
	ResultFields map[string]string `json:"result_fields"`
}

// PaginationConfig describes the pagination strategy for a board's search endpoint.
type PaginationConfig struct {
	Kind  PaginationKind `json:"kind"`
	Param string         `json:"param"`
	Start int            `json:"start"`
}

// ListingConfig describes the listing detail-fetch phase.
type ListingConfig struct {
	// Fetch controls whether the adapter needs a separate detail-page HTTP request.
	Fetch ListingFetch `json:"fetch"`
	// RawCapture specifies what portion of the response is stored verbatim in GCS.
	// Currently always "full_response".
	RawCapture string `json:"raw_capture"`
}

// IncrementalConfig drives the high-water-mark incrementality stop condition.
// The scraper stops paginating when listing posted_at falls below (hwm − OverlapBuffer).
type IncrementalConfig struct {
	// CursorField is the field name used as the incremental cursor (typically "posted_at").
	CursorField string `json:"cursor_field"`
	// OverlapBuffer is a Go duration string (e.g. "36h") re-scanned on each run so
	// late-indexed posts are not missed.
	OverlapBuffer string `json:"overlap_buffer"`
	// SafetyMaxPages is an absolute page-count cap; the primary stop condition is the HWM.
	SafetyMaxPages int `json:"safety_max_pages"`
}

// ResultFieldListingURL is the required key in SearchConfig.ResultFields that points
// at each card's listing URL.
const ResultFieldListingURL = "listing_url"

// Validate checks that the spec carries the fields a generic crawler needs to evaluate
// it. It enforces the schema constraints that an approved adapter must satisfy before
// going live (see ADR-004: declarative specs are validated against a schema before
// approval). A nil return means the spec is structurally valid; it does not guarantee
// the board endpoint is reachable.
func (s AdapterSpec) Validate() error {
	if s.Board == "" {
		return &kernel.ValidationError{Field: "board", Message: "is required"}
	}
	if s.FetchMode != FetchModeJSONAPI && s.FetchMode != FetchModeHTML {
		return &kernel.ValidationError{Field: "fetch_mode", Message: "must be json_api or html"}
	}
	if s.Search.URLTemplate == "" {
		return &kernel.ValidationError{Field: "search.url_template", Message: "is required"}
	}
	if s.Search.ResultNodePath == "" {
		return &kernel.ValidationError{Field: "search.result_node_path", Message: "is required"}
	}
	if s.Search.ResultFields[ResultFieldListingURL] == "" {
		return &kernel.ValidationError{Field: "search.result_fields.listing_url", Message: "is required"}
	}
	switch s.Search.Pagination.Kind {
	case PaginationKindQueryParam, PaginationKindCursor:
	default:
		return &kernel.ValidationError{Field: "search.pagination.kind", Message: "must be query_param or cursor"}
	}
	switch s.Listing.Fetch {
	case ListingFetchDetailPage, ListingFetchUseSearchPayload:
	default:
		return &kernel.ValidationError{Field: "listing.fetch", Message: "must be detail_page or use_search_payload"}
	}
	if _, err := time.ParseDuration(s.Incremental.OverlapBuffer); err != nil {
		return &kernel.ValidationError{Field: "incremental.overlap_buffer", Message: "must be a valid Go duration"}
	}
	if s.Incremental.SafetyMaxPages <= 0 {
		return &kernel.ValidationError{Field: "incremental.safety_max_pages", Message: "must be > 0"}
	}
	return nil
}
